# Generated by Django 2.2.5 on 2020-06-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200616_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Accuracy',
            field=models.IntegerField(null=True),
        ),
    ]
